# Generated by Django 4.1 on 2022-11-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.pengguna'),
        ),
    ]
