# Generated by Django 4.1 on 2022-11-01 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laporan', '0002_laporan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laporan',
            name='user',
        ),
    ]
