# Generated by Django 4.1 on 2022-11-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laporan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='laporanResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=60)),
                ('case_name', models.CharField(max_length=30)),
                ('status_case', models.BooleanField(null=True)),
                ('admin_response', models.CharField(max_length=100)),
                ('laporan_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='laporan.laporan')),
            ],
        ),
    ]
