# Generated by Django 4.1 on 2022-11-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_pengguna_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='konsulir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
