# Generated by Django 4.1 on 2022-11-01 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pengguna_konsulir_alter_pengguna_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengguna',
            old_name='konsulir',
            new_name='is_konsulir',
        ),
    ]
