# Generated by Django 4.1 on 2022-10-28 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curhat_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curhatadmin',
            old_name='descriprion',
            new_name='description',
        ),
    ]
