# Generated by Django 4.1 on 2022-11-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curhat_admin', '0002_rename_descriprion_curhatadmin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='curhatadmin',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
