# Generated by Django 4.1 on 2022-11-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curhat_admin', '0003_remove_curhatadmin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='curhatadmin',
            name='admin_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
