# Generated by Django 4.1 on 2022-11-01 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curhat_admin', '0003_curhatadmin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curhatadmin',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
