# Generated by Django 4.1 on 2022-11-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curhat_admin', '0004_alter_curhatadmin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curhatadmin',
            name='date',
            field=models.DateField(),
        ),
    ]
