# Generated by Django 4.1 on 2022-11-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curhat_admin', '0005_alter_curhatadmin_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curhatadmin',
            name='date',
        ),
    ]
