# Generated by Django 4.1 on 2022-10-26 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('curhat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curhatdong',
            old_name='descriprion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='curhatdong',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
